### ISSUE TITLE
MPF package

### ISSUE THREAD

**Issue by jabdoa2** [Compy/Pinix-MPF#1]
* [ ] depend on psutils
* [ ] depend on pyserial > 3.2 #3
* [ ] depend on pyserial-asyncio > 0.3 #4
* [ ] depend on ruamel.yaml latest 0.10 #5
