### ISSUE TITLE
MPF-MC package

### ISSUE THREAD

**Issue by jabdoa2** [Compy/Pinix-MPF#2]
* [ ] depend on psutil
* [ ] depend on MPF #1 
* [ ] depend on kivy 1.10.1 #6
* [ ] depend on ruamel.yaml latest 0.10 #5
